[project]
name = "ping-pong-pals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "itsdangerous>=2.2.0",
    "newsflash>=0.3.4",
    "sqlalchemy>=2.0.54",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "ping_pong_pals"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]

[tool.fastapi]
entrypoint = "main:app"