# Generated by Django 4.1.5 on 2023-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_league_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
