# Generated by Django 4.1.5 on 2023-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_game_league_alter_game_loser_alter_game_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='participants',
            field=models.ManyToManyField(related_name='leagues', to='scoreboard.player'),
        ),
    ]
