# Generated by Django 4.1.5 on 2023-12-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0011_currentrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.CharField(default='league-slug', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
