# Generated by Django 5.0.1 on 2024-01-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scoreboard', '0012_league_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupkey',
            name='add_as_member_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.league'),
        ),
    ]
