# Generated by Django 4.1.5 on 2023-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser_points',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='winner_points',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
